In [2]:
import pandas as pd
from madrid_rental.database.connection import get_engine

In [3]:
engine = get_engine()

query = """
    SELECT a.precio, a.superficie, a.habitaciones, a.banos, b.nombre AS barrio
    FROM anuncios a
    JOIN barrios b ON a.barrio_id = b.id
"""

df = pd.read_sql(query, engine)
df.head()

    precio  superficie  habitaciones  banos       barrio
0  2317.06       131.0             3      1   Arganzuela
1   517.98        40.0             2      1        Usera
2   601.34        55.0             1      1  Carabanchel
3   734.11        60.0             2      3     Vallecas
4  1365.49        80.0             2      3   Arganzuela

In [4]:
df_modelo = pd.get_dummies(df, columns=["barrio"])
df_modelo.head()

,precio,superficie,habitaciones,banos,barrio_Arganzuela,barrio_Carabanchel,barrio_Centro,barrio_Chamartín,barrio_Chamberí,barrio_Retiro,barrio_Salamanca,barrio_Tetuán,barrio_Usera,barrio_Vallecas
0,2317.06,131.0,3,1,True,False,False,False,False,False,False,False,False,False
1,517.98,40.0,2,1,False,False,False,False,False,False,False,False,True,False
2,601.34,55.0,1,1,False,True,False,False,False,False,False,False,False,False
3,734.11,60.0,2,3,False,False,False,False,False,False,False,False,False,True
4,1365.49,80.0,2,3,True,False,False,False,False,False,False,False,False,False